//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_ENGLISH_NEPALI_DATE
    {
        public Nullable<int> NEPALI_YEAR { get; set; }
        public Nullable<int> MONTH_CD { get; set; }
        public Nullable<int> NO_OF_DAYS { get; set; }
        public string NEPALI_ST_DATE { get; set; }
        public Nullable<System.DateTime> ENG_ST_DATE { get; set; }
        public Nullable<System.DateTime> ENG_END_DATE { get; set; }
        public string FISCAL_YR { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> ENTERED_DT { get; set; }
        public string NEPALI_ST_DT_YEAR_MON { get; set; }
        public string NEPALI_ST_DT_YEAR_DAY { get; set; }
        public string NEW_NEP_DATE { get; set; }
        public int NEP_DATE_NUM { get; set; }
    }
}
