//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class engDateList
    {
        public int engDateId { get; set; }
        public int engYear { get; set; }
        public int engMonth { get; set; }
        public string engMonthName { get; set; }
        public int daysCount { get; set; }
    }
}
