//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workList
    {
        public int workListId { get; set; }
        public string workListType { get; set; }
        public string mun { get; set; }
        public int time { get; set; }
        public string users { get; set; }
        public System.DateTime date { get; set; }
    }
}
